version: '3'

services:
  dashboard:
    image: node:16
    command: bash -c "npm i && npm run dev"
    working_dir: /app
    volumes:
      - .:/app
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      monero_net:
        ipv4_address: 172.16.0.3
  node:
    image: sethsimmons/simple-monerod
    restart: unless-stopped
    volumes:
      - monero-chain-data:/home/monero/.bitmonero
      - monero-wallet-data:/wallet
    command:
      - --rpc-bind-ip=172.16.0.2
      - --rpc-bind-port=18081
      - --confirm-external-bind
      - --no-igd
      - --no-zmq
      - --enable-dns-blocklist
    networks:
      monero_net:
        ipv4_address: 172.16.0.2

volumes:
  monero-chain-data:
  monero-wallet-data:

networks:
  monero_net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
