version: '3'

services:
  dashboard:
    image: brechtdoran/monero-node-dashboard:latest
    restart: unless-stopped
    environment:
      - MONERO_HOST=172.16.0.2
      - MONERO_PORT=18081
    ports:
      - 3000:3000
    networks:
      monero_net:
        ipv4_address: 172.16.0.3
  node:
    image: sethsimmons/simple-monerod
    restart: unless-stopped
    volumes:
      - monero-chain-data:/home/monero/.bitmonero
      - monero-wallet-data:/wallet
    ports:
      - 18080:18080
      - 18089:18089
    command:
      - --rpc-bind-ip=172.16.0.2
      - --rpc-bind-port=18081
      - --confirm-external-bind
      - --rpc-restricted-bind-ip=0.0.0.0
      - --rpc-restricted-bind-port=18089
      - --no-igd
      - --no-zmq
      - --enable-dns-blocklist
    networks:
      monero_net:
        ipv4_address: 172.16.0.2

volumes:
  monero-chain-data:
  monero-wallet-data:

networks:
  monero_net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
