version: '3'

services:
  dashboard:
    image: brechtdoran/monero-node-dashboard:latest
    restart: unless-stopped
    environment:
      - MONERO_HOST=localhost
      - MONERO_PORT=18081
    network_mode: service:node
  node:
    image: sethsimmons/simple-monerod
    restart: unless-stopped
    volumes:
      - monero-chain-data:/home/monero/.bitmonero
      - monero-wallet-data:/wallet
    ports:
      - 18080:18080
      - 18089:18089
      - 3000:3000
    command:
      - --rpc-restricted-bind-ip=0.0.0.0
      - --rpc-restricted-bind-port=18089
      - --no-igd
      - --no-zmq
      - --enable-dns-blocklist
    networks:
      - monero_net

volumes:
  monero-chain-data:
  monero-wallet-data:

networks:
  monero_net:
    driver: bridge
